version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Jakarta
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=n8n-test.boy3030.my.id
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n-test.boy3030.my.id/
      - TELEGRAM_API_TOKEN=8368581479:AAHXRpdQnHKH3W4K-hG0vQ9nJNaIpz_yhwc
    volumes:
      - ./n8n_data:/home/node/.n8n
