version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Jakarta
      - WEBHOOK_URL=https://your-app.onrender.com/
      - N8N_HOST=your-app.onrender.com
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - TELEGRAM_API_KEY=123456:abcdef   # ganti dengan token bot kamu
      - EXECUTIONS_PROCESS=main
    volumes:
      - ./n8n_data:/home/node/.n8n
    restart: unless-stopped
